-- MySQL Script generated by MySQL Workbench
-- Thu Mar 13 18:27:51 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema academiadb
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `academiadb` DEFAULT CHARACTER SET utf8 ;
USE `academiadb` ;

-- -----------------------------------------------------
-- Table `academiadb`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academiadb`.`aluno` (
  `idaluno` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `data_nascimento` DATE NULL,
  `cpf` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `data_matricula` DATE NULL,
  PRIMARY KEY (`idaluno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academiadb`.`instrutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academiadb`.`instrutor` (
  `idinstrutor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `cpf` VARCHAR(45) NULL,
  `especialiade` VARCHAR(45) NULL,
  `data_contratacao` DATE NULL,
  PRIMARY KEY (`idinstrutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academiadb`.`aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academiadb`.`aula` (
  `idaula` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `descricao` VARCHAR(45) NULL,
  `data_horario_inicio` DATETIME NULL,
  `data_horario_fim` DATETIME NULL,
  `aulacol` VARCHAR(45) NULL,
  `idinstrutor` INT NOT NULL,
  PRIMARY KEY (`idaula`, `idinstrutor`),
  INDEX `fk_aula_instrutor_idx` (`idinstrutor` ASC) VISIBLE,
  CONSTRAINT `fk_aula_instrutor`
    FOREIGN KEY (`idinstrutor`)
    REFERENCES `academiadb`.`instrutor` (`idinstrutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academiadb`.`aluno_aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academiadb`.`aluno_aula` (
  `aluno_idaluno` INT NOT NULL,
  `aula_idaula` INT NOT NULL,
  PRIMARY KEY (`aluno_idaluno`, `aula_idaula`),
  INDEX `fk_aluno_has_aula_aula1_idx` (`aula_idaula` ASC) VISIBLE,
  INDEX `fk_aluno_has_aula_aluno1_idx` (`aluno_idaluno` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_has_aula_aluno1`
    FOREIGN KEY (`aluno_idaluno`)
    REFERENCES `academiadb`.`aluno` (`idaluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_has_aula_aula1`
    FOREIGN KEY (`aula_idaula`)
    REFERENCES `academiadb`.`aula` (`idaula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
